### ISSUE TITLE
Make SwiftGL a CocoaPod

### ISSUE THREAD

**Issue by akshay23** [SwiftGL/Math#2]
It would be awesome it SwiftGL was a CocoaPod so projects that use [CocoaPods](http://cocoadocs.org) instead of the Swift Package Manager can also it. Please let me know if you want me to do this for you guys to speed up the process. Thanks.

**Comment by jkolb** [comment]
I'll get it started today.

**Comment by jkolb** [comment]
Done

**Comment by akshay23** [comment]
Awesome. Thanks so much!!
