### ISSUE TITLE
Rename Math CocoaPod to SGLMath to stay consistent with SPM

### ISSUE THREAD

**Issue by akshay23** [SwiftGL/Math#3]
Sorry to bug you about this again, but would it be possible to change the name of the pod to SGLMath instead of just Math to be consistent with swift package manager? This would work really well if we are using both options in different settings without having to change `import SGLMath` to `import Math`.

**Comment by jkolb** [comment]
I thought that it had to match the Github name, but that actually didn't work for the OpenGL project so had to make it SGLOpenGL to fix compiler errors and it worked but hopefully it can be renamed, not sure how CocoaPods handles that. I'll give it a try.

**Comment by jkolb** [comment]
OK done.
